In [1]:
from models import  vit_b_16_age_recognizer, resent101_age_recogniser
from preprocessor import RetinaPreprocessor
import torch

In [6]:
model = resent101_age_recogniser()
state_dict = torch.load('./Checkpoint/resnet101/best.pt')
# model = vit_b_16_age_recognizer()
# state_dict = torch.load('./Checkpoint/vit_16_B/best.pt')
model_state_dict = state_dict['model_state_dict']
model.load_state_dict(model_state_dict)
model.eval()

ResNetAgeRecognizer(
  (backbone): ResNet(
    (conv1): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
    (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (relu): ReLU(inplace=True)
    (maxpool): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
    (layer1): Sequential(
      (0): Bottleneck(
        (conv1): Conv2d(64, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (conv3): Conv2d(64, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (bn3): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu): ReLU(inplace=True)
        (downsample): Sequentia

In [7]:
preprocessor = RetinaPreprocessor()

In [14]:
child = preprocessor.preprocess('./sample/4.jpg')
profile = preprocessor.preprocess('./sample/20.jpg')
celebrity = preprocessor.preprocess('./sample/celebrity2.jpg')
child_feat = model(child.unsqueeze(0))
profile_feat = model(profile.unsqueeze(0))
celebrity_feat = model(celebrity.unsqueeze(0))

In [15]:
from torch import cosine_similarity
print((cosine_similarity(child_feat, profile_feat) + 1) / 2)
print((cosine_similarity(child_feat, celebrity_feat) + 1) / 2)
print((cosine_similarity(celebrity_feat, profile_feat) + 1) / 2)

tensor([0.6136], grad_fn=<DivBackward0>)
tensor([0.4725], grad_fn=<DivBackward0>)
tensor([0.3502], grad_fn=<DivBackward0>)
