In [3]:
from models import  vit_b_16_age_recognizer, resent101_age_recogniser
from preprocessor import RetinaPreprocessor
import torch

In [4]:
model = vit_b_16_age_recognizer()
# model = resent101_age_recogniser()
# state_dict = torch.load('./Checkpoint/resnet101/best.pt')
state_dict = torch.load('./Checkpoint/vit_16_B/best.pt')
model_state_dict = state_dict['model_state_dict']
model.load_state_dict(model_state_dict)
model.eval()

ViTAgeRecognizer(
  (backbone): VisionTransformer(
    (conv_proj): Conv2d(3, 768, kernel_size=(16, 16), stride=(16, 16))
    (encoder): Encoder(
      (dropout): Dropout(p=0.0, inplace=False)
      (layers): Sequential(
        (encoder_layer_0): EncoderBlock(
          (ln_1): LayerNorm((768,), eps=1e-06, elementwise_affine=True)
          (self_attention): MultiheadAttention(
            (out_proj): NonDynamicallyQuantizableLinear(in_features=768, out_features=768, bias=True)
          )
          (dropout): Dropout(p=0.0, inplace=False)
          (ln_2): LayerNorm((768,), eps=1e-06, elementwise_affine=True)
          (mlp): MLPBlock(
            (0): Linear(in_features=768, out_features=3072, bias=True)
            (1): GELU(approximate='none')
            (2): Dropout(p=0.0, inplace=False)
            (3): Linear(in_features=3072, out_features=768, bias=True)
            (4): Dropout(p=0.0, inplace=False)
          )
        )
        (encoder_layer_1): EncoderBlock(
          (ln

In [5]:
preprocessor = RetinaPreprocessor()

In [9]:
child = preprocessor.preprocess('./sample/4.jpg')
profile = preprocessor.preprocess('./sample/23.jpg')
celebrity = preprocessor.preprocess('./sample/celebrity.jpg')
child_feat = model(child.unsqueeze(0))
profile_feat = model(profile.unsqueeze(0))
celebrity_feat = model(celebrity.unsqueeze(0))

In [10]:
from torch import cosine_similarity
print((cosine_similarity(child_feat, profile_feat) + 1) / 2)
print((cosine_similarity(child_feat, celebrity_feat) + 1) / 2)
print((cosine_similarity(celebrity_feat, profile_feat) + 1) / 2)

tensor([0.7915], grad_fn=<DivBackward0>)
tensor([0.6059], grad_fn=<DivBackward0>)
tensor([0.7735], grad_fn=<DivBackward0>)
